default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  username: root
  password: 

development:
  <<: *default
  database: carpoolers_development

test: &test
  <<: *default
  host: 127.0.0.1
  database: carpoolers_test

production:
  <<: *default
  database: carpoolers_production
  username: carpoolers
  password: <%= ENV['CARPOOLERS_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test
